version: '3.8'

services:
  centro-drugstore-app:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /usr/src/app
    volumes:
      - /home/jretondo/proyectos/loza-rufeil/backend_v1:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - centro-drugstore-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - centro-drugstore-network

networks:
  centro-drugstore-network:
    driver: bridge
