version: '3.8'

services:
  centro-drugstore-app:
    image: node-point-sell-dev:1.0
    working_dir: /app
    volumes:
      - /home/jretondo/proyectos/centro-drugstore/backend_v1:/app
      - /app/node_modules
      - ./public:/app/public
    ports:
      - '3003:3003'
      - '3005:3005'
    env_file:
      - .env
