version: '3.8'

services:
  centro-drugstore-app:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - /home/backend/public_html/centro-drugstore/production:/app
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002:/etc/letsencrypt/live/nekoadmin.com.ar-0002:ro
      - /app/node_modules
    ports:
      - '3003:3003'
      - '3005:3005'
    env_file:
      - .env
