version: '3.8'

services:
  centro-drugstore-app:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - /home/jretondo/proyectos/centro-drugstore/backend_v1:/app
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002/fullchain.pem:/app/fullchain.pem
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002/privkey.pem:/app/privkey.pem
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
      - '3005:3005'
    env_file:
      - .env
