version: '3.8'

services:
  centro-drugstore-app:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /usr/src/app
    volumes:
      - /home/jretondo/proyectos/centro-drugstore/backend_v1:/usr/src/app
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002/fullchain.pem:/usr/src/app/fullchain.pem
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002/privkey.pem:/usr/src/app/privkey.pem
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
      - '3005:3005'
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
          storage: '6G'
