version: '3.8'

services:
  centro-drugstore-app:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002/fullchain.pem:/etc/letsencrypt/live/nekoadmin.com.ar-0002/fullchain.pem:ro
      - /etc/letsencrypt/live/nekoadmin.com.ar-0002/private.pem:/etc/letsencrypt/live/nekoadmin.com.ar-0002/private.pem:ro
    ports:
      - '3003:3003'
      - '3005:3005'
    env_file:
      - .env
