version: '3.8'

services:
  centro-drugstore-app:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - /home/backend/public_html/centro-drugstore/production:/app
      - /app/node_modules
    ports:
      - '3003:3003'
      - '3005:3005'
    env_file:
      - .env
